[build]
    command = "npm run build"
    functions = "api"
    publish = "public"

[functions]
    included_files = ["data/**"]
    
[[redirects]]
    from = "/api/v1/*"
    to = "/.netlify/functions/:splat"
    status = 200

# For Single Page Application
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200